### ISSUE TITLE
 cdnjs.cloudflare.com breaks when using DOH ipv4 list

### ISSUE THREAD

**Issue by DrGonzoNL** [Sekhan/TheGreatWall#6]
I use your DOH IP list in my OPNSense firewall, it will block 104.16.132.229 on port 443.
This breaks cdnjs.cloudflare.com, result is that websites using this will load very very slow. An example is www.rtvnoord.nl 
An NSLookup of cdnjs.cloudflare.com gives: 
Non-authoritative answer:
Name:    cdnjs.cloudflare.com
Addresses:  2606:4700::6810:85e5
          2606:4700::6810:84e5
          104.16.132.229
          104.16.133.229

Is it possible to remove these IP's? If not, is there documentation or some proof that these IP's provide DoH? If yes, then I have to consider if whitelisting is an option.

**Comment by Sekhan** [comment]
Thanks for your feedback :innocent: 
Theses IP adresses were linked to _dns.cloudflare.com_ but, indeed, it seems that this subdomain doesn't provide DoH and redirect to Cloudflare presentation of their DNS service.

```
Name :  dns.cloudflare.com
Addresses:  2606:4700::6810:85e5
          2606:4700::6810:84e5
          104.16.132.229
          104.16.133.229
```
I'll remove them immediatly !
